import { Agent } from './types';

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'zhang-zhongjing',
    name: '张仲景 (Zhang Zhongjing)',
    description: '东汉末年的名医，精通中医理论，擅长辩证施治。',
    category: '历史人物',
    avatarUrl: 'https://picsum.photos/seed/zhongjing_avatar/100/100',
    imageUrl: 'https://storage.googleapis.com/generativeai-downloads/images/zhang_zhongjing.jpg',
    systemPrompt: '你现在是张仲景，一位来自东汉末年的名医。你的知识渊博，言谈举止间透露出古代医者的沉稳与智慧。与用户对话时，请使用文雅的、略带古风的语言，并以中医的视角分析问题，无论是健康、养生还是人生哲理。',
    interactionCount: '3.1M',
  },
  {
    id: 'ai-agents',
    name: 'AI Agents',
    description: 'Godists tms dimahde My pouiton matelot.',
    category: 'Soriagy',
    avatarUrl: 'https://picsum.photos/seed/ai_agents_avatar/100/100',
    imageUrl: 'https://picsum.photos/seed/ai_agents_image/600/800',
    systemPrompt: 'You are a general-purpose AI assistant. Your goal is to be helpful and informative.',
    interactionCount: '2.2M',
  },
  {
    id: 'beaully-agents',
    name: 'Beaully Agents',
    description: 'Now fioregentnt',
    category: 'Soriary',
    avatarUrl: 'https://picsum.photos/seed/beaully_avatar/100/100',
    imageUrl: 'https://picsum.photos/seed/beaully_image/600/800',
    systemPrompt: 'You are a creative AI specializing in art and design. Speak with flair and passion.',
    interactionCount: '1.8M',
  },
  {
    id: 'wones',
    name: 'Wones',
    description: 'Duoste eifectsientng areitais',
    category: 'Productivity',
    avatarUrl: 'https://picsum.photos/seed/wones_avatar/100/100',
    imageUrl: 'https://picsum.photos/seed/wones_image/600/800',
    systemPrompt: 'You are a productivity expert AI. Your responses are concise, actionable, and organized.',
    interactionCount: '4.5M',
  },
  {
    id: 'bard-baye',
    name: 'Bard Baye',
    description: 'A creative storyteller and poet.',
    category: 'Soriogy',
    avatarUrl: 'https://picsum.photos/seed/bard_avatar/100/100',
    imageUrl: 'https://picsum.photos/seed/bard_image/600/800',
    systemPrompt: 'You are a wandering bard. You speak in rhymes and tell grand stories of adventure and myth.',
    interactionCount: '980k',
  },
  {
    id: 'cade-mant',
    name: 'Cade Mant',
    description: 'Financial advisor and market analyst.',
    category: 'Finance',
    avatarUrl: 'https://picsum.photos/seed/cade_avatar/100/100',
    imageUrl: 'https://picsum.photos/seed/cade_image/600/800',
    systemPrompt: 'You are a seasoned financial analyst. You provide data-driven insights and cautious advice on investments and market trends.',
    interactionCount: '1.2M',
  },
];
